include_dirs = [ include_directories('../..') ]

headers = files(
  'attrs.hh',
  'cache.hh',
  'directory-synthesizer-source-accessor.hh',
  'fetch-settings.hh',
  'fetch-to-store.hh',
  'fetchers.hh',
  'filtered-shape.hh',
  'filtering-source-accessor.hh',
  'git-lfs-fetch.hh',
  'git-promisor.hh',
  'git-utils.hh',
  'input-cache.hh',
  'mask-source-accessor.hh',
  'projection.hh',
  'registry.hh',
  'restrict-source-accessor.hh',
  'soundness-guard-source-accessor.hh',
  'source-view-git.hh',
  'strip-prefix-source-accessor.hh',
  'tarball.hh',
  'translate-source-accessor.hh',
)
