#!/usr/bin/env bash

source common.sh

TODO_NixOS

cd "$TEST_ROOT"

test_fetch_file () {
    echo foo > test_input

    input_hash="$(nix hash path test_input)"
    # The object hash of a flat file is its blob id: sha256 of "blob 4\0foo\n"
    # (git hash-object --object-format=sha256), as SRI.
    input_tree_hash=sha256-R9asqCdW/y5h5TUgv98fqmyG2TO+SFTrNIQMV9EuDIU=

    nix eval --impure --file - <<EOF
    let
        tree = builtins.fetchTree { type = "file"; url = "file://$PWD/test_input"; };
    in
    # \`narHash\` is the lazy attribute, computed by a walk when forced; \`treeHash\` is the name's hash.
    assert (tree.narHash == "$input_hash");
    assert (tree.treeHash == "$input_tree_hash");
    assert builtins.readFile tree == "foo\n";
    tree
EOF
}

# Make sure that `http(s)` and `file` flake inputs are properly extracted when
# they should be, and treated as opaque files when they should be
test_file_flake_input () {
    rm -fr "$TEST_ROOT/testFlake";
    mkdir "$TEST_ROOT/testFlake";
    pushd testFlake

    mkdir inputs
    echo foo > inputs/test_input_file
    echo '{ outputs = { self }: { }; }' > inputs/flake.nix
    tar cfa test_input.tar.gz inputs
    cp test_input.tar.gz test_input_no_ext
    input_tarball_hash="$(nix hash path test_input.tar.gz)"
    input_directory_hash="$(nix hash path inputs)"
    # The SHA-256 git tree id of `inputs` (entries flake.nix, test_input_file,
    # both 100644), the name the lock carries for the unpacked inputs.  The
    # tarball's own blob id is not a constant (tar's timestamps), so the
    # file inputs are compared with the language's `treeHash` below.
    input_directory_tree_hash=sha256-+MHjp8KPMSRWG7feirfbEjpKBjN52kUUKm0Z10ecd2E=

    cat <<EOF > flake.nix
    {
        inputs.no_ext_default_no_unpack = {
            url = "file://$PWD/test_input_no_ext";
            flake = false;
        };
        inputs.no_ext_explicit_unpack = {
            url = "tarball+file://$PWD/test_input_no_ext";
            flake = false;
        };
        inputs.tarball_default_unpack = {
            url = "file://$PWD/test_input.tar.gz";
            flake = false;
        };
        inputs.tarball_explicit_no_unpack = {
            url = "file+file://$PWD/test_input.tar.gz";
            flake = false;
        };
        inputs.flake_no_ext = {
            url = "file://$PWD/test_input_no_ext";
        };
        outputs = { ... }: {};
    }
EOF

    nix flake update
    nix eval --file - <<EOF
    with (builtins.fromJSON (builtins.readFile ./flake.lock));

    # Non-flake inputs whose extension doesn’t match a known archive format should
    # not be unpacked by default
    assert (nodes.no_ext_default_no_unpack.locked.type == "file");
    assert (nodes.no_ext_default_no_unpack.locked.unpack or false == false);
    # The lock carries the tree hash (version 8), never the NAR hash.
    assert (nodes.no_ext_default_no_unpack.locked ? treeHash);
    assert (!(nodes.no_ext_default_no_unpack.locked ? narHash));

    # For backwards compatibility, flake inputs that correspond to the
    # old 'tarball' fetcher should still have their type set to 'tarball'
    assert (nodes.tarball_default_unpack.locked.type == "tarball");
    # Unless explicitly specified, the 'unpack' parameter shouldn’t appear here
    # because that would break older Nix versions
    assert (!nodes.tarball_default_unpack.locked ? unpack);
    assert (nodes.tarball_default_unpack.locked.treeHash == "$input_directory_tree_hash");
    assert (!(nodes.tarball_default_unpack.locked ? narHash));

    # Explicitly passing the unpack parameter should enforce the desired behavior
    assert (nodes.no_ext_explicit_unpack.locked.treeHash == nodes.tarball_default_unpack.locked.treeHash);
    assert (nodes.tarball_explicit_no_unpack.locked.treeHash == nodes.no_ext_default_no_unpack.locked.treeHash);

    # Flake inputs should always be tarballs
    assert (nodes.flake_no_ext.locked.type == "tarball");

    true
EOF

    # The file input's lock entry is the language's `treeHash` for the same
    # file, and its NAR hash -- the lazy attribute, forced here -- is the
    # file's, so the version-7 evidence is still checked, through the shim.
    [[ $(nix eval --impure --raw --expr "(builtins.fetchTree { type = \"file\"; url = \"file://$PWD/test_input_no_ext\"; }).treeHash") == $(jq -r .nodes.no_ext_default_no_unpack.locked.treeHash flake.lock) ]]
    [[ $(nix eval --impure --raw --expr "(builtins.fetchTree { type = \"file\"; url = \"file://$PWD/test_input_no_ext\"; }).narHash") == "$input_tarball_hash" ]]
    [[ $(nix eval --impure --raw --expr "(builtins.fetchTree { type = \"tarball\"; url = \"file://$PWD/test_input.tar.gz\"; }).narHash") == "$input_directory_hash" ]]

    # Test tarball URLs on the command line.
    [[ $(nix flake metadata --json "file://$PWD/test_input_no_ext" | jq -r .resolved.type) = tarball ]]

    popd

    [[ -z "${NIX_DAEMON_PACKAGE-}" ]] && return 0

    # Ensure that a lockfile generated by the current Nix for tarball inputs
    # can still be read by an older Nix

    cat <<EOF > flake.nix
    {
        inputs.tarball = {
            url = "file://$PWD/test_input.tar.gz";
            flake = false;
        };
        outputs = { self, tarball }: {
            foo = builtins.readFile "\${tarball}/test_input_file";
        };
    }
    nix flake update

    clearStore
    "$NIX_DAEMON_PACKAGE/bin/nix" eval .#foo
EOF
}

# attrPos is fetchTree call pos
test_fetch_file_attr_pos () {
    echo pos_content > pos_input

    cat > pos_test.nix <<EOF
let
  tree = builtins.fetchTree {
    type = "file";
    url = "file://$PWD/pos_input";
  };
  checkAttr = name:
    builtins.addErrorContext "while checking the position of attribute '\${name}'" (
      let
        pos = builtins.unsafeGetAttrPos name tree;
      in
        assert pos != null;
        assert pos.line == 2;
        assert pos.file == "$PWD/pos_test.nix";
        true
    );
in
  assert tree?narHash; # sanity
  assert tree?treeHash; # sanity
  assert tree?outPath; # sanity
  assert builtins.all checkAttr (builtins.attrNames tree);
  true
EOF

    [[ $(nix eval --impure --file pos_test.nix) == "true" ]]
}

test_fetch_file
test_file_flake_input
test_fetch_file_attr_pos
