# Public headers directory

include_dirs = [ include_directories('../../..') ]

headers = files(
  'derivation.hh',
  'derived-path.hh',
  'https-store.hh',
  'libstore-network.hh',
  'libstore.hh',
  'nix_api_store.hh',
  'outputs-spec.hh',
  'path-info-json-v3.hh',
  'path.hh',
  'protocol.hh',
  'temp-local-store.hh',
  'test-main.hh',
)
