on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

jobs:

  build:
    strategy:
      fail-fast: false
    runs-on: ${{ inputs.os }}
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          determinate: true
      - uses: DeterminateSystems/flakehub-cache-action@main
      - run: echo "system=$(nix eval --impure --raw --expr 'builtins.currentSystem')" >> "$GITHUB_OUTPUT"
        id: system
      - run: nix build .# .#binaryTarball --no-link -L
      - run: nix build .#binaryTarball --out-link tarball
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.system.outputs.system }}
          path: ./tarball/*.xz
