on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      manual:
        required: false
        type: boolean
        default: false

jobs:

  build:
    strategy:
      fail-fast: false
    runs-on: ${{ inputs.os }}
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          flakehub: true
      - uses: DeterminateSystems/flakehub-cache-action@main
      - run: nix build . .#binaryTarball -L
