name: "CI"

on:
  pull_request:
  push:
    branches:
      - detsys-main
      - main
      - master

permissions:
  id-token: "write"
  contents: "read"

jobs:
  eval:
    runs-on: UbuntuLatest32Cores128G
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: DeterminateSystems/nix-installer-action@main
      with:
        flakehub: true
    - run: nix flake show --all-systems --json

  build_x86_64-linux:
    uses: ./.github/workflows/build.yml
    with:
      os: UbuntuLatest32Cores128G

  build_aarch64-linux:
    uses: ./.github/workflows/build.yml
    with:
      os: UbuntuLatest32Cores128GArm

  build_aarch64-darwin:
    uses: ./.github/workflows/build.yml
    with:
      os: macos-latest

  test_x86_64-linux:
    uses: ./.github/workflows/test.yml
    needs: build_x86_64-linux
    with:
      os: UbuntuLatest32Cores128G

  test_aarch64-linux:
    uses: ./.github/workflows/test.yml
    needs: build_aarch64-linux
    with:
      os: UbuntuLatest32Cores128GArm

  test_aarch64-darwin:
    uses: ./.github/workflows/test.yml
    needs: build_aarch64-darwin
    with:
      os: macos-latest

  vm_tests:
    needs: build_x86_64-linux
    runs-on: UbuntuLatest32Cores128G
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          flakehub: true
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: |
          nix build -L \
            .#hydraJobs.tests.functional_user \
            .#hydraJobs.tests.githubFlakes \
            .#hydraJobs.tests.nix-docker \
            .#hydraJobs.tests.tarballFlakes \
            ;

  flake_regressions:
    needs: vm_tests
    runs-on: UbuntuLatest32Cores128G
    steps:
      - name: Checkout nix
        uses: actions/checkout@v4
      - name: Checkout flake-regressions
        uses: actions/checkout@v4
        with:
          repository: DeterminateSystems/flake-regressions
          path: flake-regressions
      - name: Checkout flake-regressions-data
        uses: actions/checkout@v4
        with:
          repository: DeterminateSystems/flake-regressions-data
          path: flake-regressions/tests
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          flakehub: true
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix build -L --out-link ./new-nix && PATH=$(pwd)/new-nix/bin:$PATH MAX_FLAKES=25 flake-regressions/eval-all.sh
