name: Release Branch

concurrency:
  group: release

on:
  push:
    branches:
      # NOTE: make sure any branches here are also valid directory names,
      # otherwise creating the directory and uploading to s3 will fail
      - "main"

permissions:
  id-token: "write"
  contents: "read"

jobs:
  release-branch:
    uses: ./.github/workflows/upload-release.yml
    secrets: inherit
