name: Release Tags

concurrency:
  group: release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write # In order to upload artifacts to GitHub releases
  id-token: write # In order to request a JWT for AWS auth

jobs:
  release-tag:
    uses: ./.github/workflows/upload-release.yml
    secrets: inherit
